# -*- coding: utf-8 -*-
"""Decision Tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_sNXt_Bmv5OBwky0ycHi4k4aeYOWrrKV
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn import utils
from sklearn.tree import export_graphviz
import graphviz

df= pd.read_csv("travel insurance.csv")

df.head()

x =df[["Net Sales"]]
y =df[["Distribution Channel"]]
x_train,y_train,x_test,y_test= train_test_split (x,y,test_size=0.5,random_state=5)
print (y_test)

st_x = StandardScaler()
x_train = st_x.fit_transform(x_train)
y_train = st_x.fit_transform(x_train)

print (y_train)

classifier= DecisionTreeClassifier(criterion='gini',random_state=0)
#lab_enc = preprocesing.LabelEncoder(y)

classifier.fit(x,y)
y_pred = classifier.predict(x)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y,y_pred)
cm

graphviz.Source (export_graphviz (classifier,feature_names = x.columns,filled=True,class_names=['1','2','3','4','5'],out_file=None))